/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {IndicatorSummaryType} from './IndicatorSummaryType';
import {SpatialUnitSummaryType} from './SpatialUnitSummaryType';

/**
 * The HarvesterOutputType model module.
 * @module model/HarvesterOutputType
 * @version 0.0.1
 */
export class HarvesterOutputType {
  /**
   * Constructs a new <code>HarvesterOutputType</code>.
   * output generated by a harvesting process
   * @alias module:model/HarvesterOutputType
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HarvesterOutputType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HarvesterOutputType} obj Optional instance to populate.
   * @return {module:model/HarvesterOutputType} The populated <code>HarvesterOutputType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HarvesterOutputType();
      if (data.hasOwnProperty('spatialUnitSummary'))
        obj.spatialUnitSummary = ApiClient.convertToType(data['spatialUnitSummary'], [SpatialUnitSummaryType]);
      if (data.hasOwnProperty('indicatorSummary'))
        obj.indicatorSummary = ApiClient.convertToType(data['indicatorSummary'], [IndicatorSummaryType]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/SpatialUnitSummaryType>} spatialUnitSummary
 */
HarvesterOutputType.prototype.spatialUnitSummary = undefined;

/**
 * @member {Array.<module:model/IndicatorSummaryType>} indicatorSummary
 */
HarvesterOutputType.prototype.indicatorSummary = undefined;

