/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {IndicatorSpatialUnitMappingResultType} from './IndicatorSpatialUnitMappingResultType';
import {SummaryType} from './SummaryType';
import {SummaryTypeErrorsOccurred} from './SummaryTypeErrorsOccurred';

/**
 * The IndicatorSummaryType model module.
 * @module model/IndicatorSummaryType
 * @version 0.0.1
 */
export class IndicatorSummaryType extends SummaryType {
  /**
   * Constructs a new <code>IndicatorSummaryType</code>.
   * @alias module:model/IndicatorSummaryType
   * @class
   * @extends module:model/SummaryType
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>IndicatorSummaryType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IndicatorSummaryType} obj Optional instance to populate.
   * @return {module:model/IndicatorSummaryType} The populated <code>IndicatorSummaryType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IndicatorSummaryType();
      SummaryType.constructFromObject(data, obj);
      if (data.hasOwnProperty('numberOfHarvestedTimestamps'))
        obj.numberOfHarvestedTimestamps = ApiClient.convertToType(data['numberOfHarvestedTimestamps'], 'Number');
      if (data.hasOwnProperty('harvestedTimestamps'))
        obj.harvestedTimestamps = ApiClient.convertToType(data['harvestedTimestamps'], ['Date']);
      if (data.hasOwnProperty('harvestedSpatialUnits'))
        obj.harvestedSpatialUnits = ApiClient.convertToType(data['harvestedSpatialUnits'], [IndicatorSpatialUnitMappingResultType]);
    }
    return obj;
  }
}

/**
 * @member {Number} numberOfHarvestedTimestamps
 */
IndicatorSummaryType.prototype.numberOfHarvestedTimestamps = undefined;

/**
 * @member {Array.<Date>} harvestedTimestamps
 */
IndicatorSummaryType.prototype.harvestedTimestamps = undefined;

/**
 * @member {Array.<module:model/IndicatorSpatialUnitMappingResultType>} harvestedSpatialUnits
 */
IndicatorSummaryType.prototype.harvestedSpatialUnits = undefined;

