/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {IndicatorSpatialUnitMappingType} from './IndicatorSpatialUnitMappingType';
import {SummaryTypeErrorsOccurred} from './SummaryTypeErrorsOccurred';

/**
 * The IndicatorSpatialUnitMappingResultType model module.
 * @module model/IndicatorSpatialUnitMappingResultType
 * @version 0.0.1
 */
export class IndicatorSpatialUnitMappingResultType extends IndicatorSpatialUnitMappingType {
  /**
   * Constructs a new <code>IndicatorSpatialUnitMappingResultType</code>.
   * @alias module:model/IndicatorSpatialUnitMappingResultType
   * @class
   * @extends module:model/IndicatorSpatialUnitMappingType
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>IndicatorSpatialUnitMappingResultType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IndicatorSpatialUnitMappingResultType} obj Optional instance to populate.
   * @return {module:model/IndicatorSpatialUnitMappingResultType} The populated <code>IndicatorSpatialUnitMappingResultType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IndicatorSpatialUnitMappingResultType();
      IndicatorSpatialUnitMappingType.constructFromObject(data, obj);
      if (data.hasOwnProperty('numberOfHarvestedFeatures'))
        obj.numberOfHarvestedFeatures = ApiClient.convertToType(data['numberOfHarvestedFeatures'], 'Number');
      if (data.hasOwnProperty('errorOccurred'))
        obj.errorOccurred = SummaryTypeErrorsOccurred.constructFromObject(data['errorOccurred']);
    }
    return obj;
  }
}

/**
 * @member {Number} numberOfHarvestedFeatures
 */
IndicatorSpatialUnitMappingResultType.prototype.numberOfHarvestedFeatures = undefined;

/**
 * @member {module:model/SummaryTypeErrorsOccurred} errorOccurred
 */
IndicatorSpatialUnitMappingResultType.prototype.errorOccurred = undefined;

