/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AuthenticationType} from './AuthenticationType';

/**
 * The KomMonitorInstanceType model module.
 * @module model/KomMonitorInstanceType
 * @version 0.0.1
 */
export class KomMonitorInstanceType {
  /**
   * Constructs a new <code>KomMonitorInstanceType</code>.
   * access information about specific KomMonitor instance
   * @alias module:model/KomMonitorInstanceType
   * @class
   * @param url {String} the url to the data management service of the instance.
   */
  constructor(url) {
    this.url = url;
  }

  /**
   * Constructs a <code>KomMonitorInstanceType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KomMonitorInstanceType} obj Optional instance to populate.
   * @return {module:model/KomMonitorInstanceType} The populated <code>KomMonitorInstanceType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KomMonitorInstanceType();
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('authentication'))
        obj.authentication = AuthenticationType.constructFromObject(data['authentication']);
    }
    return obj;
  }
}

/**
 * the url to the data management service of the instance.
 * @member {String} url
 */
KomMonitorInstanceType.prototype.url = undefined;

/**
 * @member {module:model/AuthenticationType} authentication
 */
KomMonitorInstanceType.prototype.authentication = undefined;

