/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SummaryType} from './SummaryType';
import {SummaryTypeErrorsOccurred} from './SummaryTypeErrorsOccurred';

/**
 * The SpatialUnitSummaryType model module.
 * @module model/SpatialUnitSummaryType
 * @version 0.0.1
 */
export class SpatialUnitSummaryType extends SummaryType {
  /**
   * Constructs a new <code>SpatialUnitSummaryType</code>.
   * @alias module:model/SpatialUnitSummaryType
   * @class
   * @extends module:model/SummaryType
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>SpatialUnitSummaryType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SpatialUnitSummaryType} obj Optional instance to populate.
   * @return {module:model/SpatialUnitSummaryType} The populated <code>SpatialUnitSummaryType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SpatialUnitSummaryType();
      SummaryType.constructFromObject(data, obj);
      if (data.hasOwnProperty('numberOfHarvestedFeatures'))
        obj.numberOfHarvestedFeatures = ApiClient.convertToType(data['numberOfHarvestedFeatures'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} numberOfHarvestedFeatures
 */
SpatialUnitSummaryType.prototype.numberOfHarvestedFeatures = undefined;

