/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SummaryTypeErrorsOccurred model module.
 * @module model/SummaryTypeErrorsOccurred
 * @version 0.0.1
 */
export class SummaryTypeErrorsOccurred {
  /**
   * Constructs a new <code>SummaryTypeErrorsOccurred</code>.
   * @alias module:model/SummaryTypeErrorsOccurred
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SummaryTypeErrorsOccurred</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SummaryTypeErrorsOccurred} obj Optional instance to populate.
   * @return {module:model/SummaryTypeErrorsOccurred} The populated <code>SummaryTypeErrorsOccurred</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SummaryTypeErrorsOccurred();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} message
 */
SummaryTypeErrorsOccurred.prototype.message = undefined;

/**
 * @member {Number} code
 */
SummaryTypeErrorsOccurred.prototype.code = undefined;

