"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.HarvesterOutputType = void 0;

var _ApiClient = require("../ApiClient");

var _IndicatorSummaryType = require("./IndicatorSummaryType");

var _SpatialUnitSummaryType = require("./SpatialUnitSummaryType");

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

/**
 * The HarvesterOutputType model module.
 * @module model/HarvesterOutputType
 * @version 0.0.1
 */
var HarvesterOutputType = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>HarvesterOutputType</code>.
   * output generated by a harvesting process
   * @alias module:model/HarvesterOutputType
   * @class
   */
  function HarvesterOutputType() {
    _classCallCheck(this, HarvesterOutputType);
  }
  /**
   * Constructs a <code>HarvesterOutputType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HarvesterOutputType} obj Optional instance to populate.
   * @return {module:model/HarvesterOutputType} The populated <code>HarvesterOutputType</code> instance.
   */


  _createClass(HarvesterOutputType, null, [{
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new HarvesterOutputType();
        if (data.hasOwnProperty('spatialUnitSummary')) obj.spatialUnitSummary = _ApiClient.ApiClient.convertToType(data['spatialUnitSummary'], [_SpatialUnitSummaryType.SpatialUnitSummaryType]);
        if (data.hasOwnProperty('indicatorSummary')) obj.indicatorSummary = _ApiClient.ApiClient.convertToType(data['indicatorSummary'], [_IndicatorSummaryType.IndicatorSummaryType]);
      }

      return obj;
    }
  }]);

  return HarvesterOutputType;
}();
/**
 * @member {Array.<module:model/SpatialUnitSummaryType>} spatialUnitSummary
 */


exports.HarvesterOutputType = HarvesterOutputType;
HarvesterOutputType.prototype.spatialUnitSummary = undefined;
/**
 * @member {Array.<module:model/IndicatorSummaryType>} indicatorSummary
 */

HarvesterOutputType.prototype.indicatorSummary = undefined;