/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {HarvesterInputType} from '../model/HarvesterInputType';
import {HarvesterOutputType} from '../model/HarvesterOutputType';

/**
* Harvester service.
* @module api/HarvesterApi
* @version 0.0.1
*/
export class HarvesterApi {

    /**
    * Constructs a new HarvesterApi. 
    * @alias module:api/HarvesterApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the executeHarvesting operation.
     * @callback moduleapi/HarvesterApi~executeHarvestingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HarvesterOutputType{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Perform harvesting process according to submitted config.
     * Perform harvesting process according to submitted config.
     * @param {module:model/HarvesterInputType} body details necessary to execute harvesting process
     * @param {module:api/HarvesterApi~executeHarvestingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    executeHarvesting(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling executeHarvesting");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = HarvesterOutputType;

      return this.apiClient.callApi(
        '/harvest/execute', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}