/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KomMonitorHarvesterApi);
  }
}(this, function(expect, KomMonitorHarvesterApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AuthenticationType', function() {
      beforeEach(function() {
        instance = new KomMonitorHarvesterApi.AuthenticationType();
      });

      it('should create an instance of AuthenticationType', function() {
        // TODO: update the code to test AuthenticationType
        expect(instance).to.be.a(KomMonitorHarvesterApi.AuthenticationType);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property username (base name: "username")', function() {
        // TODO: update the code to test the property username
        expect(instance).to.have.property('username');
        // expect(instance.username).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property keycloakUrl (base name: "keycloakUrl")', function() {
        // TODO: update the code to test the property keycloakUrl
        expect(instance).to.have.property('keycloakUrl');
        // expect(instance.keycloakUrl).to.be(expectedValueLiteral);
      });

      it('should have the property keycloakRealm (base name: "keycloakRealm")', function() {
        // TODO: update the code to test the property keycloakRealm
        expect(instance).to.have.property('keycloakRealm');
        // expect(instance.keycloakRealm).to.be(expectedValueLiteral);
      });

      it('should have the property keycloakClientId (base name: "keycloakClientId")', function() {
        // TODO: update the code to test the property keycloakClientId
        expect(instance).to.have.property('keycloakClientId');
        // expect(instance.keycloakClientId).to.be(expectedValueLiteral);
      });

    });
  });

}));
