/*
 * KomMonitor Harvester API
 * KomMonitor Harvester API to harvest/transfer spatial data from one instance to another
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KomMonitorHarvesterApi);
  }
}(this, function(expect, KomMonitorHarvesterApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PeriodOfValidityType', function() {
      beforeEach(function() {
        instance = new KomMonitorHarvesterApi.PeriodOfValidityType();
      });

      it('should create an instance of PeriodOfValidityType', function() {
        // TODO: update the code to test PeriodOfValidityType
        expect(instance).to.be.a(KomMonitorHarvesterApi.PeriodOfValidityType);
      });

      it('should have the property validStartDate (base name: "validStartDate")', function() {
        // TODO: update the code to test the property validStartDate
        expect(instance).to.have.property('validStartDate');
        // expect(instance.validStartDate).to.be(expectedValueLiteral);
      });

      it('should have the property validEndDate (base name: "validEndDate")', function() {
        // TODO: update the code to test the property validEndDate
        expect(instance).to.have.property('validEndDate');
        // expect(instance.validEndDate).to.be(expectedValueLiteral);
      });

    });
  });

}));
